### ISSUE TITLE
`merge` action is skipped instead of waiting for required checks to pass

### ISSUE THREAD

**Issue by KnutZuidema** [linear-b/gitstream#228] opened 2023-07-04 10:58 UTC
We are using an automation to merge @dependabot PRs, as described in the [Dependabot integration documentation](https://docs.gitstream.cm/integrations/dependabot/). However, the action to merge the PR is skipped with the message: 
> Waiting for required checks and approvals, details: Required status check "<redacted>" is pending. You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.

I would expect the `merge` action to wait for all checks to pass, before attempting to merge the PR.

**Comment by vim-zz** [comment] 2023-07-04 11:48
@KnutZuidema did you try setting `wait_for_all_checks: true` -- see here: https://docs.gitstream.cm/automation-actions/#merge

**Comment by KnutZuidema** [comment] 2023-07-04 12:53
@vim-zz yes, it's set. I am using the same configuration as is proposed in the Dependabot integration:
```yaml
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  approve_dependabot:
    if:
      - {{ branch.name | includes(term="dependabot") }}
      - {{ branch.author | includes(term="dependabot") }}
    run:
      - action: approve@v1
      - action: add-label@v1
        args:
          label: "approved-dependabot"
      - action: merge@v1
        args:
          wait_for_all_checks: true
          squash_on_merge: true

```

**Comment by vim-zz** [comment] 2023-07-04 13:03
@KnutZuidema beside the message is hows is there any functional issue? does it merge when all checks are Ok?

**Comment by KnutZuidema** [comment] 2023-07-04 14:55
@vim-zz yes, there is a functional issue. The action is skipped altogether, so nothing gets merged.

**Comment by KnutZuidema** [comment] 2023-07-06 13:45
@vim-zz will the fix be available in v1?

**Comment by KnutZuidema** [comment] 2023-07-07 09:16
@vim-zz it looks like the fix was not deployed yet or it doesn't fix the issue. Right now, the exact same issue persists.

**Comment by vim-zz** [comment] 2023-07-09 12:48
Hey @KnutZuidema, can you check this on a new PR? If you still get see this happening on a new PR, please share a screenshot of the PR checks area

**Comment by KnutZuidema** [comment] 2023-07-14 10:12
@vim-zz the issue still persists. I've attached screenshots of the check area, as well as the 
output of the merge action.
![image](https://github.com/linear-b/gitstream/assets/28651746/db90811b-112f-4bcb-aedd-e15dc71bb23d)
![image](https://github.com/linear-b/gitstream/assets/28651746/c42b375d-7071-4f47-9a49-ec826db14d85)

**Comment by BenLloydPearson** [comment] 2023-07-26 13:36
@KnutZuidema I replicated your configuration and was able to successfully run it [here](https://github.com/blp-test-dev/hello-gitStream/pull/66) (note: I changed the trigger conditions slightly to test), which leads me to believe it may be something else that is blocking gitStream from merging.

I have a few questions that could help us narrow this down.
* Do you have any branch protection rules configured for the repo for things like requiring more than one review, or requiring a review from specific individuals? It's possible that gitStream's approval isn't enough to merge the PR.
* Approximately how long does it take for your CI processes to finish? I'm wondering if there might be a timeout issue.
* Do you have any org-level automations that are being overridden at the repo level?

**Comment by KnutZuidema** [comment] 2023-07-26 14:15
@BenLloydPearson thanks for looking into this!

The CI takes ~7 minutes to complete.

We do have a branch protection rule requiring an approving review from somebody with write access. That could be the reason.

There are no org level restrictions that I am aware of.

**Comment by vim-zz** [comment] 2023-08-17 14:53
@KnutZuidema we could not reproduce the issue, can we set a call to understand more and try to figure out the problem? You can schedule a meeting directly to my calendar: https://calendly.com/ofer-linearb-17tr/meeting

**Comment by KnutZuidema** [comment] 2023-08-30 15:34
Hi @vim-zz, thanks for taking the time to look into it. I'll try to come back to this, but I'm more or less constantly OOO until mid-October.

**Comment by PiStefania** [comment] 2023-09-18 07:40
Hello @vim-zz, i have the same issue regarding a dependabot pr that we need to merge automatically using gitstream. The merge action is skipped with the following message: "Waiting for required checks and approvals, details: 5 of 9 required status checks are in progress." However, the required checks are all passed. Could this be a timeout issue?

**Comment by PavelLinearB** [comment] 2023-11-08 11:43
Hi @KnutZuidema, @PiStefania
We have changed the mechanism of the `wait_for_all_checks` argument.
According to the new change, the action will be performed after all checks are completed and concluded with one of the following: `neutral`, `skipped`, or `success`, along with a bugfix in case gitStream was marked as a required check.

Could you verify that this fix works for you?
Thanks!

**Closed** 2023-11-09 14:28 UTC
Labels: bug, 👀.
