### ISSUE TITLE
Workflow will fail sometimes rescind its automatic approval

### ISSUE THREAD

**Issue by ianwesleyarmstrong** [linear-b/gitstream#2] opened 2022-12-14 22:32 UTC
**Describe the bug**

Workflow will fail sometimes fail due to files cached on the runner. The odd part is my workflow will run and perform the automations, but then rescind the auto-approval and dismiss a stale review a minute or so later. On subsequent commits, the check will display gitstream workflow not found.

**To Reproduce**
This is happening in a private repo, but my `gitstream.cm` is just a loose adaption of the example.

**Expected behavior**
The auto-approval should stay valid

**Screenshots**

Stale Review
![image](https://user-images.githubusercontent.com/24705212/207727621-22e90311-c3d8-487b-bf5e-0e12d0a72303.png)

GitHub Actions log
![image](https://user-images.githubusercontent.com/24705212/207727984-62280d2a-0baf-4fb4-9f90-68ec052e6707.png)

**Git provider**
The Git provider been used

**Additional context**

**Comment by ShakedZrihen** [comment] 2022-12-15 12:49
@ianwesleyarmstrong can you please attach here your `gitstream.cm` file + repository and PR number?

thanks!

**Comment by ianwesleyarmstrong** [comment] 2022-12-15 15:07
Thanks! The repo is `opencareer/tf-infra` and it started on PR #75. On the newer PR's it is showing as successful, but the workflow isn't actually getting triggered.

gitstream.cm
```
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  welcome_message:
    if:
      - {{ repo.contributors | isFirstCommit(branch.author) }}
    run:
      - action: add-comment@v1
        args:
          comment: |
            Welcome @{{ pr.author }}!

  estimated_time_to_review:
    if:
      - true
    run:
      - action : add-label@v1
        args:
          label: '{{ calc.etr }} min review'
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}

  safe_changes:
    # The `if` key has a list of conditions, each condition is specified as a Jinja expression
    # in a double curly braces. Expressions are evaluated by gitStream on a PR when triggered.
    if:
      # Given the PR code changes, check that only formatting changes were made
      - {{ is.formatting or is.docs or is.tests }}
    # `run` key has a list of actions, which are executed one by one whenever the automation
    # conditions are met.
    run:
      # When the changes are validated as formatting only, you can help to speed up the review
      # by adding a label that marks it accordingly.
      - action: add-label@v1
        args:
          label: 'safe-changes'
      # You can uncomment the following action to get gitStream can even automatically approve
      # such PRs to save reviewers time for such changes.
      # - action: approve@v1

  admin_autoapprove:
    if:
      - {{ is.admin }}
    run:
      - action: approve@v1

  review_cicd:
    if:
      - {{ files | match(regex=r/.github\/workflows\/.*\.yml/) | some }}
    run:
      - action: add-reviewers@v1
        args:
          team_reviewers: [infrastructure]

  snowflake_access:
    if:
      - {{ is.snowflake_access }}
    run:
      - action: add-reviewers@v1
        args:
          team_reviewers: [snowflake-infrastructure]
      - action: add-comment@v1
        args:
          comment: |
            Snowflake ...

  aws_changes:
    if:
      - {{ is.aws and not is.admin }}
    run:
      - action: add-label@v1
        args:
          label: 'aws'
      - action: add-reviewers@v1
        args:
          team_reviewers: [aws-infrastructure]

  snowflake_changes:
    if:
      - {{ is.snowflake and not is.admin }}
    run:
      - action: add-label@v1
        args:
          label: 'snowflake'
      - action: add-reviewers@v1
        args:
          team_reviewers: [snowflake-infrastructure]

calc:
  etr: {{ branch | estimatedReviewTime }}
is:
  formatting: {{ source.diff.files | isFormattingChange }}
  docs: {{ files | allDocs }}
  tests: {{ files | allTests }}
  terragrunt: {{ files | match(regex=r/(...)\/terragrunt.hcl/) | some }}
  admin: {{ pr.author | includes(list=['ianwesleyarmstrong']) }}
  aws: {{ files | match(regex=r/aws\/(...)/) | some }}
  snowflake: {{ files | match(regex=r/snowflake\/(...)/) | some }}
  snowflake_access: {{ files | match(regex=r/(...)\/(roles)|(users)\.yaml/) | some }}

**Comment by ianwesleyarmstrong** [comment] 2022-12-15 15:29
i'm now running into this error as well:

```
Running tag v1.76
Already on 'share-refresh'
Already on 'share-refresh'
ARGS:  { regex: /.github\/workflows\/.*\.yml/, __keywords: true }
ARGS:  { regex: /(...)\/terragrunt.hcl/, __keywords: true }
/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:577
    return file.includes(term);
                ^

TypeError: Cannot read properties of null (reading 'includes')
    at /node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:577:17
    at Array.some (<anonymous>)
    at Context.parseIncludes (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:576:114)
    at eval (eval at _compile (/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:38:59)
    at _callee$ (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:778:13)
    at tryCatch (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:96:17)
    at Generator._invoke (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:76:24)
    at Generator.next (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:127:21)
    at asyncGeneratorStep (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:360:24)
    at _next (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:382:9)
```

**Comment by ianwesleyarmstrong** [comment] 2022-12-15 18:57
Hi,

The workflow is breaking before the rules can finish evaluating. I am adding a new directory/file, so maybe its erroring out on some kind of file diff?

```
docker.io/gitstream/rules-engine:latest

> gitstream-rules-engine@1.0.0 start
> node src/app.js

Running tag v1.76
Switched to branch 'main'
Switched to branch '***'
fatal: no such path snowflake/et27231/us-east-2/production/databases/***/terragrunt.hcl in main
ARGS:  { regex: /.github\/workflows\/.*\.yml/, __keywords: true }
ARGS:  { regex: /(...)\/terragrunt.hcl/, __keywords: true }
/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:577
    return file.includes(term);
                ^

TypeError: Cannot read properties of null (reading 'includes')
    at /node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:577:17
    at Array.some (<anonymous>)
    at Context.parseIncludes (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:576:114)
    at eval (eval at _compile (/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:44:59)
    at _callee$ (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:778:13)
    at tryCatch (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:96:17)
    at Generator._invoke (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:76:24)
    at Generator.next (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:127:21)
    at asyncGeneratorStep (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:360:24)
    at _next (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:382:9)
```

**Comment by ShakedZrihen** [comment] 2022-12-15 22:23
hello again!
first of all -> Im happy that you are trying our tool :) we are still in early stages so we are more than happy to get inputs from users.
I pushed a fix to a problem we had in this area and I can't reproduced this bug anymore in my repository.
Can you try again and let me know if it fixed at your end as well?

Thanks, 
Shaked

**Comment by ianwesleyarmstrong** [comment] 2022-12-15 22:58
Of course! I have some thoughts about the developer experience if you would be interested.

It looks like it's cleared up as far as I can tell. I have a few more PR's out that I would like to check before closing for good

**Comment by ShakedZrihen** [comment] 2022-12-16 05:30
Ill be happy to hear from you!
This is my email: shaked@linearb.io

You can send me email and we can schedule a call with the product team/ open some chat with them :)

**Comment by ianwesleyarmstrong** [comment] 2022-12-19 22:24
Just saw this pop up again under similar circumstances

`/home/runner/work/_temp/d9d2aa2b-8a68-458f-ab85-3791bc7cfb7b.sh: line 10: unexpected EOF while looking for matching `''`

**Comment by ShakedZrihen** [comment] 2022-12-20 09:23
hi @ianwesleyarmstrong !
ill give it another check :)
the `.cm` is still the one you attached here, right?

**Comment by vim-zz** [comment] 2023-01-12 11:22
i’m closing this bug, @ianwesleyarmstrong if you still get this issue feel free to reopen it or open a new issue

**Closed by vim-zz** 2023-01-12 11:22 UTC
Labels: bug

**Comment by ianwesleyarmstrong** [comment] 2023-01-12 14:55
I'm getting a similar bug where GitStream runs in the first commit of a PR, but on any subsequent commits it shows the GitStream check as skipped. Would you like me to open another issue or continue here?
