### ISSUE TITLE
rules-engine: Fatal error when PR changelist contains paths with spaces, exit code 40

### ISSUE THREAD

**Issue by mishagp** [linear-b/gitstream#12] opened 2023-01-20 16:30 UTC
**Describe the bug**

gitStream checks seem to fail on PRs that contained any added/modified files with spaces and return an exit code of 40.

**To Reproduce**

Have an added/modified file in a PR with a path that contains spaces. For example: `xxxx/yyyy/zzzz/firstname lastname.html`.

We would see an error in the action log like so:

```
fatal: path 'xxxx/yyyy/zzzz/firstname' does not exist in `corresponding commit hash`
fatal: path 'xxxx/yyyy/zzzz/firstname' does not exist in `corresponding commit branch`
fatal: path 'xxxx/yyyy/zzzz/firstname' exists on disk, but not in 'master'
Error: Failed getting PR context.
Error: Process completed with exit code 40.
```

**Comment by vim-zz** [comment] 2023-01-29 15:47
@mishagp we could not reproduce this issue

1. can you share the `.cm` automation file you use? 
2. can you make verify it still hapenning?

**Comment by mishagp** [comment] 2023-01-31 22:08
Will verify and follow up this week 👍🏻 This was using the same config from #13.

**Comment by vim-zz** [comment] 2023-02-05 15:19
@mishagp I am closing this for now

**Closed by vim-zz** 2023-02-05 15:19 UTC
Labels: bug
